HomePage/urls.py
from django.conf.urls import url, include
from . import views

app_name = "HomePage"

urlpatterns = [
	
	url(r'^$', views.HomePage, name='HomePage')
]

groceriesForMyEvents/urls.py
from django.contrib import admin, auth
from django.urls import include, path
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('myGroceries.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

myGroceries/urls.py
from django.urls import path, include
from . import views

app_name = "myGroceries"

urlpatterns = [
	
	path('', views.homepage, name='homepage'), #page d'accueil
	path('event/create/', views.create_event, name='create_event'), #création d'événement
	path('event/<name_event>/delete/', views.delete_event, name='delete_event'), #delete l'événement action
	#path('event/<name_event>/update/', views.update_event, name='update_event'), #update l'événement
	path('event/<name_event>/', views.event_detail, name='event_detail'), #détail de l'événement
	path('event/invite/<name_event>/', views.invitation_to_my_event, name='invitation_to_my_event'), #inviter à l'événement
	path('event/invite/<name_event>/act', views.invitation_to_my_event_act, name='invitation_to_my_event_act'), #inviter à l'événement action
	path('event/invite/<name_event>/accept', views.invitation_to_event_accept, name='invitation_to_event_accept'), #accepter l'événement action
	path('event/invite/<name_event>/refuse', views.invitation_to_event_refuse, name='invitation_to_event_refuse'), #refuser l'événement action
	path('event/participe/<name_event>/cancel', views.participation_to_event_cancel, name='participation_to_event_cancel'), #annuler la participation à l'événement action
	#path('event/participe/<name_event>/<id_invite>/delete', views.participation_to_my_event_delete, name='participation_to_my_event_delete'), #supprimer une participation à mon événement action
	#path('event/invite/<name_event>/<id_invite>/delete', views.invitation_to_my_event_delete, name='invitation_to_my_event_delete'), #supprimer une invitation à mon événement action
	path('event/<name_event>/courses/', views.add_products_to_event, name='add_products_to_event'), #ajouter des produits à sa liste de courses
	path('event/<name_event>/courses/act', views.add_products_to_event_act, name='add_products_to_event_act'), #ajouter des courses action
	#path('event/<name_event>/courses/<id_invite>/delete/', views.delete_products_to_event, name='delete_products_to_event'), #suppression de ses courses action
] 

HomePage/models.py
from django.db import models

# Create your models here.

myGroceries/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime


class Event(models.Model):
    name = models.CharField(max_length=250)
    start_date = models.DateField(auto_now = False)
    end_date = models.DateField(auto_now = False)
    description = models.TextField(default='')
    host = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Invitation(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    guest = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.event.name)


class Product(models.Model):
    name = models.TextField()

    def __str__(self):
        return self.name


class Participation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    product = models.ManyToManyField(Product)

    def __str__(self):
        return self.user.username + " - " + self.event.name

myGroceries/forms.py
from django import forms
from .models import *

class EventForm(forms.ModelForm):
	
	class Meta:
		model = Event
		fields = ('name', 'description', 'start_date', 'end_date', 'description')

HomePage/views.py
from django.shortcuts import render

# Create your views here.
def HomePage(request):
	template = 'HomePage/HomePage.html'
	return render(request, template, {})

myGroceries/views.py
from .models import *
from .forms import EventForm
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth  import get_user_model
from django.contrib.auth.decorators import login_required
import datetime


#Page d'accueil
@login_required
def homepage(request):
	logged_in_user = request.user #récupération de l'utilisateur
	now = datetime.datetime.now() #récupération de la date d'aujourd'hui
	logged_in_user_events = Event.objects.filter(host=logged_in_user, end_date__gte=now) #récupération de tous les événements créés par l'utilisateur et exclu les événements passés
	logged_in_user_invitations = Invitation.objects.filter(guest=logged_in_user) #récupération de tous les événements auquel l'utilisateur est invité
	logged_in_user_participations = Participation.objects.filter(user=logged_in_user) #récupération de tous les événements auquel l'utilisateur est invité
	template = 'myGroceries/homepage.html'
	context = {'hostingevents' : logged_in_user_events, 'guesttoevents' : logged_in_user_invitations, 'guesttoparticipants' : logged_in_user_participations, 'user': request.user}
	return render(request, template, context)


#Page de vue de l'événement
@login_required
def event_detail(request, name_event):
	logged_in_user = request.user #récupération de l'utilisateur
	event = get_object_or_404(Event, name=name_event)
	invited = Invitation.objects.filter(event=event)
	guest_groceries = Participation.objects.filter(event=event)
	template = 'myGroceries/event_detail.html'
	context={'event': event, 'invited': invited, 'guest_groceries': guest_groceries}
	return render(request, template, context)


#Page de création d'un événement
@login_required
def create_event(request):
	template = 'myGroceries/create_event.html'
	if request.method == "POST":
		form = EventForm(request.POST)
		if form.is_valid():
			event = form.save(commit=False)
			event.host = request.user #affiliation de l'id de l'utilisateur à l'id_host
			event.save()
			return redirect('myGroceries:invitation_to_my_event', name_event=event.name) #si le formulaire est validé, renvoi vers l'invitation d'utilisateurs à l'event
#		participation = Participation(user=request.user, event=event.name)
#		participation.save()
	else:
		form = EventForm()
	return render(request, template, {'form': form})


#Action de suppression d'un événement
@login_required
def delete_event(request, name_event):
	try:
		event = get_object_or_404(Event, name=name_event)
		event.delete()
	except ObjectDoesNotExist:
		pass
	return redirect("myGroceries:homepage")


#Page de modification d'un événement
#@login_required
#def update_event(request, name_event):
#	try:
#		event = get_object_or_404(Event, name=name_event)
#		if event.start_date != request.POST.get("start_date"):
#			event.start_date = request.POST.get("start_date")
#		if event.end_date != request.POST.get("end_date").replace("\\xa0", ""):
#			event.end_date = request.POST.get("end_date").replace("\\xa0", "")
#		if event.description != request.POST.get("description").replace("\\xa0", ""):
#			event.description = request.POST.get("description").replace("\\xa0", "")
#		event.save()
#	except ObjectDoesNotExist:
#		pass
#	return redirect("/event/" + name_event + "/")



#Page d'invitation à l'événement
@login_required
def invitation_to_my_event(request, name_event):
	logged_in_user = request.user #récupération de l'utilisateur
	event = get_object_or_404(Event, name=name_event, host=logged_in_user) #erreur 404 si l'event n'existe pas ou si l'utilisateur n'a pas créé cet événement
	list_user = get_user_model()
	users = list_user.objects.all()
	template = 'myGroceries/invitation_to_my_event.html'
	context = {'event' : event, 'users': users, 'host': logged_in_user}
	return render(request, template, context)



#Action d'invitation à l'événement
@login_required
def invitation_to_my_event_act(request, name_event):
	logged_in_user = request.user #récupération de l'utilisateur
	event = get_object_or_404(Event, name=name_event, host=logged_in_user) #erreur 404 si l'event n'existe pas ou si l'utilisateur n'a pas créé cet événement
	user_invited = request.POST.getlist("users_post") # récupération de la liste d'user
	# ajout en bdd
	for u in user_invited:
		user = User.objects.get(username=u)
		try:
			# si présent en base pass
			Invitation.objects.get(event=event, guest=user)
		except ObjectDoesNotExist:
			# sinon ajout
			invitation = Invitation(event=event, guest=user)
			invitation.save()
	return redirect("myGroceries:event_detail", name_event=name_event)


#Action d'acceptation de l'invitation à l'événement
@login_required
def invitation_to_event_accept(request, name_event):
	logged_in_user = request.user #récupération de l'utilisateur
	event = get_object_or_404(Event, name=name_event) #erreur 404 si l'event n'existe pas ou si l'utilisateur n'a pas créé cet événement
	# delete invitation add participation
	invitation = Invitation.objects.get(event=event, guest=logged_in_user)
	invitation.delete()
	participation = Participation(user=logged_in_user, event=event)
	participation.save()
	return redirect("myGroceries:homepage")


#Action de refus de l'invitation à l'événement
@login_required
def invitation_to_event_refuse(request, name_event):
	logged_in_user = request.user #récupération de l'utilisateur
	event = get_object_or_404(Event, name=name_event) #erreur 404 si l'event n'existe pas ou si l'utilisateur n'a pas créé cet événement
	# delete invitation
	invitation = Invitation.objects.get(event=event, guest=logged_in_user)
	invitation.delete()
	return redirect("myGroceries:homepage")


#Action d'annulation de la participation à l'événement
@login_required
def participation_to_event_cancel(request, name_event):
	logged_in_user = request.user #récupération de l'utilisateur
	event = get_object_or_404(Event, name=name_event) #erreur 404 si l'event n'existe pas ou si l'utilisateur n'a pas créé cet événement
	# delete invitation
	participation = Participation.objects.get(event=event, user=logged_in_user)
	participation.delete()
	return redirect("myGroceries:homepage")


# Action de suppression d'un participant à mon événement
#@login_required
#def participation_to_my_event_delete(request, name_event, id_invite):
#	event = get_object_or_404(Event, name=name_event) #erreur 404 si l'event n'existe pas ou si l'utilisateur n'a pas créé cet événement
#	participation = Participation.objects.get(event=event, user=id_invite)
#	participation.delete()
#	return redirect("myGroceries:event_detail")


# Action de suppression d'un invité à mon événément
#@login_required
#def invitation_to_my_event_delete(request, name_event, id_invite):
#	event = get_object_or_404(Event, name=name_event) #erreur 404 si l'event n'existe pas ou si l'utilisateur n'a pas créé cet événement
#	invitation = Invitation.objects.get(event=event, guest=id_invite)
#	invitation.delete()
#	return redirect("myGroceries:event_detail")


#Page d'ajout de produits à la liste de courses de l'utilisateur
@login_required
def add_products_to_event(request, name_event):
	event = get_object_or_404(Event, name=name_event) #erreur 404 si l'event n'existe pas ou si l'utilisateur n'a pas créé cet événement
	products = Product.objects.all()
	template = 'myGroceries/add_products_to_event.html'
	context = {'event' : event, 'products': products}
	return render(request, template, context)


#Action d'ajout de produits à la liste de courses de l'utilisateur
@login_required
def add_products_to_event_act(request, name_event):
	logged_in_user = request.user
	products_added = request.POST.getlist("products_post")
	event = get_object_or_404(Event, name=name_event)
	for p in products_added:
		product = Product.objects.get(name=p)
		try:
			participation = get_object_or_404(Participation, event=event)
			participation.product.add(product)
		except ObjectDoesNotExist:
				pass
	return redirect("myGroceries:event_detail", name_event=name_event)

#Action de suppression de produits à la liste de courses de l'utilisateur
#@login_required
#def delete_products_to_event(request, name_event):
#	product = get_object_or_404(Product, name=name)
#	product.delete()
#	return redirect("/event/" + str(name_event))

templates/myGroceries/add_products_to_event.html
{% extends 'myGroceries/layout.html' %}

{% block title %}Ajouter des produits à mes courses{% endblock %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'myGroceries:homepage' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'myGroceries:event_detail' name_event=event.name %}">{{ event.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Ajouter des courses</li>
  </ol>
</nav>

    <form action="{% url 'myGroceries:add_products_to_event_act' name_event=event.name %}" method="post">
        {% csrf_token %}
        <div class="table-responsive">
            <table class="table">
        {% for product in products %}
            <tr class="table-success">
                <td><input type="checkbox" name="products_post" value="{{ product.name }}"> {{ product.name }}</td>
            </tr>
        {% endfor %}
            <tr>
                <td><button type="submit" class="btn">Ajouter</button></td>
            </tr>
        </table>
        </div>
    </form>

{% endblock %}

templates/myGroceries/create_event.html
{% extends 'myGroceries/layout.html' %}
{% load widget_tweaks %}
{% block title %}Votre événement{% endblock %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'myGroceries:homepage' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Votre événement</li>
  </ol>
</nav>

    <form method="POST" class="event-form">{% csrf_token %}
        {{ form.non_field_errors }}
<div class="form-group">
    {{ form.name.errors }}
    <label for="{{ form.name.id_for_label }}">Nom :</label>
    {{ form.name|add_class:"form-control" }}
</div>
<div class="form-group">
    {{ form.description.errors }}
    <label for="{{ form.description.id_for_label }}">Description :</label>
    {{ form.description|add_class:"form-control" }}
</div>
<div class="form-group">
    {{ form.start_date.errors }}
    <label for="{{ form.start_date.id_for_label }}">Date de début :</label>
    {{ form.start_date|add_class:"form-control" }}
</div>
<div class="form-group">
    {{ form.end_date.errors }}
    <label for="{{ form.end_date.id_for_label }}">Date de fin :</label>
    {{ form.end_date|add_class:"form-control" }}
</div>
        <button type="submit" class="save btn">Continuer</button>
    </form>
    {% endblock %}

templates/myGroceries/event_detail.html
{% extends 'myGroceries/layout.html' %}

{% block title %}{{ event.name }}{% endblock %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'myGroceries:homepage' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ event.name }}</li>
  </ol>
</nav>

<p>Nom : {{ event.name }}
{% if user == event.host %}
	(<a href="{% url 'myGroceries:delete_event' name_event=event.name %}">Supprimer</a>)
{% endif %}</p>
<p>Description : {{ event.description }}</p>
<p>Dates : du {{ event.start_date }} au {{ event.end_date }}</p>
<br/>

<div class="table-responsive">
 	<table class="table">
 		{% if user == event.host %}
 		<tr>
 			<td colspan="2"><a href="{% url 'myGroceries:invitation_to_my_event' name_event=event.name %}">Inviter</a></td>
 		</tr>
 		{% endif %}
		{% for guest in guest_groceries %}
		<tr>
			<td>
				{{ guest.user.username }}
			</td>
			<td>{% for c in guest.product.all %}- {{c}}<br/> {% endfor %}{% if guest.user == user %}<a href="{% url 'myGroceries:add_products_to_event' name_event=event.name %}">+ ajouter</a>{% endif %}</td>
		</tr>
		{% endfor %}
		{% for invite in invited %}
 		<tr>
 			<td colspan="2" style="color: grey;">
 				{{ invite.guest.username}}</td>
 		</tr>
 		{% endfor %}
	</table>
</div>
{% endblock %}

templates/myGroceries/homepage.html
{% extends 'myGroceries/layout.html' %}

{% block title %}Accueil{% endblock %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Home</li>
  </ol>
</nav>

<h3>Mes événements ({{ hostingevents|length }})<a class='btn btn-light' style='margin-bottom:5px' href="{% url 'myGroceries:create_event' %}"><span class='glyphicon glyphicon-plus'></span></a></h3>


<div class="table-responsive">
 <table class="table">
{% for hostingevent in hostingevents %}
	<tr>
		<td><a  href="{% url 'myGroceries:event_detail' name_event=hostingevent.name %}">{{ hostingevent.name }}</a></td>
		<td>{{ hostingevent.start_date }} au {{ hostingevent.end_date }}</td>
		<td>{{ hostingevent.description }}</td>
	</tr>
{% endfor %}
</table>
</div>


<h3>Mes invitations ({{ guesttoevents|length }})</h3>
{% if guesttoevents %}
<div class="table-responsive">
 <table class="table">
{% for guesttoevent in guesttoevents %}
	<tr class="table-success">
		<td><a href="{% url 'myGroceries:event_detail' name_event=guesttoevent.event.name %}">{{ guesttoevent.event.name }}</a></td>
		<td>{{ guesttoevent.event.start_date }} au {{ guesttoevent.event.end_date }}</td>
		<td>{{ guesttoevent.event.description }}</td>
		<td>
			<a href="{% url 'myGroceries:invitation_to_event_accept' name_event=guesttoevent.event.name %}">accepter</a> / 
			<a href="{% url 'myGroceries:invitation_to_event_refuse' name_event=guesttoevent.event.name %}">refuser</a>
		</td>
	</tr>
{% endfor %}
</table>
</div>
{% else %}
Vous n'avez aucune invitation pour le moment
{% endif %}

<h3>Mes participations ({{ guesttoparticipants|length }})</h3>
{% if guesttoparticipants %}
<div class="table-responsive">
 <table class="table">
{% for guesttoparticipant in guesttoparticipants %}
	<tr class="table-success">
		<td><a href="{% url 'myGroceries:event_detail' name_event=guesttoparticipant.event.name %}">{{ guesttoparticipant.event.name }}</a></td>
		<td>{{ guesttoparticipant.event.start_date }} au {{ guesttoparticipant.event.end_date }}</td>
		<td>{{ guesttoparticipant.event.description }}</td>
		<td><a href="{% url 'myGroceries:participation_to_event_cancel' name_event=guesttoparticipant.event.name %}">annuler</a></td>
	</tr>
{% endfor %}
</table>
</div>
{% else %}
Vous ne participez à aucun événement actuellement
{% endif %}

{% endblock %}

templates/myGroceries/invitation_to_my_event.html
{% extends 'myGroceries/layout.html' %}

{% block title %}Inviter{% endblock %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'myGroceries:homepage' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'myGroceries:event_detail' name_event=event.name %}">{{ event.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Invités</li>
  </ol>
</nav>

    <form action="{% url 'myGroceries:invitation_to_my_event_act' name_event=event %}" method="post">
        {% csrf_token %}
        <div class="table-responsive">
            <table class="table">
        {% for user in users %}
            {% if user != host %}
            <tr class="table-success">
                <td><input type="checkbox" name="users_post" value="{{ user.username }}"> {{ user.username }}</td>
            </tr>
            {% endif %}
        {% endfor %}
            <tr>
                <td><button type="submit" class="btn">Enregistrer</button></td>
            </tr>
        </table>
        </div>
    </form>

{% endblock %}

templates/myGroceries/layout.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %}{% endblock %}</title>

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="/">
                        Groceries for my Events
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    {% if user.is_authenticated %}
                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                            {{ user.username }} <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'logout' %}">Se déconnecter</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    {% else %}
                    {% endif %}
                </div>
            </div>
        </nav>

        <div class="content container">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>